import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";
import Providers from "@/app/providers/providers";

const inter = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create Galal Mohamed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />

          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              duration: 2500,
            }}
          />

          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}